version: '3.8'

services:
  angular-app:
    build:
      context: ./surveyUI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./surveyUI:/app
    command: ng serve --host 0.0.0.0

  springboot-app:
    build:
      context: ./survey
      dockerfile: Dockerfile
    ports:
      - "8080:8080"